class Problem:
    MULTI_LABEL = 'MULTI_LABEL'
    MULTI_CLASS = 'MULTI_CLASS'
    GENERIC = 'GENERIC'


class AssignmentType:
    CRISP = 'CRISP'
    CONTINUOUS = 'CONTINUOUS'
    GENERIC = 'GENERIC'


class CoverageType:
    REDUNDANT = 'REDUNDANT'
    COMPLEMENTARY = 'COMPLEMENTARY'
    COMPLEMENTARY_REDUNDANT = 'COMPLEMENTARY_REDUNDANT'
    GENERIC = 'GENERIC'
